version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'
  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: cryptopay
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
    ports:
      - '5432:5432'
  redis:
    image: redis:7
    ports:
      - '6379:6379'
